#.travis.yml
# Jérémy Morin <jer.morin@free.fr>

language: java node_js
node_js: 
  - '0.10'
  - '0.11'
jdk: oraclejdk8
install: mvn install -DskipTests=true
before_script:
  - npm install -g grunt-cli
  - gem install sass
script: 
  - mvn test 
  - grunt test

